apiVersion: 1

datasources:
  - name: Terroir Analytics
    type: postgres
    url: ${GF_DATASOURCE_HOST}:5432
    database: terroir_ai
    user: ${GF_DATASOURCE_USER}
    secureJsonData:
      password: ${GF_DATASOURCE_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false
